[versions]
project = "3.1.8"

[libraries]
lombok = { module = "org.projectlombok:lombok", version = "1.18.26" }
jetbrains_annotations = { module = "org.jetbrains:annotations", version = "24.0.1" }

lightdream_logger = { module = "dev.lightdream:logger", version = "3.3.10" }
lightdream_filemanager = { module = "dev.lightdream:file-manager", version = "2.6.7" }
