[versions]
project = "3.1.9"

[libraries]
lombok = { module = "org.projectlombok:lombok", version = "1.18.28" }
jetbrains_annotations = { module = "org.jetbrains:annotations", version = "24.0.1" }

junit_jupiter = { module = "org.junit.jupiter:junit-jupiter ", version="5.9.3" }
junit_bom = { module = "org.junit:junit-bom", version="5.9.3" }

lightdream_logger = { module = "dev.lightdream:logger", version = "3.2.8" }
lightdream_filemanager = { module = "dev.lightdream:file-manager", version = "2.6.5" }
