[versions]
project = "3.1.3"

[libraries]
lombok = { module = "org.projectlombok:lombok", version = "1.18.26" }
jetbrains_annotations = { module = "org.jetbrains:annotations", version = "23.1.0" }

lightdream_logger = { module = "dev.lightdream:logger", version = "3.3.8" }
lightdream_filemanager = { module = "dev.lightdream:file-manager", version = "2.6.5" }
